name: Update documentation

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'main'
      github_repository:
        description: IIIF Commons repository with documentation
        required: true
      check_id:
        description: The id of the check which this workflow should update
        required: false
      github_sha:
        description: The sha on the repository which dispatched this workflow where the check is
        required: false
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      # Then checkout dependencies, this is branch we are rebasing.
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile --non-interactive

      - run: |
          git config user.name iiif-commons-documentation-updater[bot]
          git config user.email 247822+iiif-commons-documentation-updater[bot]@users.noreply.github.com
          git checkout main
          node ./scripts/update-docs.js --ci --branch=${{ github.event.inputs.branch }} --repo=${{ github.event.inputs.github_repository }}

      - run: git push origin main --force-with-lease
        continue-on-error: true

      - name: Obtain GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token@1.1.0 ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"

      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.githubAppAuth.outputs.token }}
          script: |
            github.rest.checks.update({
              owner: 'IIIF-Commons',
              repo: '${{ github.event.inputs.github_repository }}'.slice("IIIF-Commons/".length),
              check_run_id: '${{ github.event.inputs.check_id }}',
              status: 'completed',
              conclusion: 'success',
            })

